-

diff --git a/bin/import_all b/bin/import_all
--- a/bin/import_all
+++ b/bin/import_all
@@ -15,21 +15,21 @@ EXECPATH="$(dirname "$0")/.."
 
 [ -z "$EXECPATH" ] && fail "$0 must be called with explicit path"
 
-cd "$EXECPATH"
-
 [ -z "$ISABELLE_HOME" ] && ISABELLE_HOME="$(isatool getenv -b ISABELLE_HOME)"
 ISATOOL="$ISABELLE_HOME/bin/isatool"
 
+cd "$EXECPATH"
 for SRC in ex/src_hs/*.hs
 do
   DST=ex/dst_thy/
   ./bin/import_file "$SRC" "$DST" || fail "could not import $SRC"
 done
 
+cp -vu adapt/Prelude.thy ex/dst_thy/
 cd ex/dst_thy/
 for THY in *.thy
 do
   THY_NAME="$(basename $THY .thy)"
   DST="../../ex/dst_hs/"
-  "$ISATOOL" codegen HOL "$THY_NAME" "\"$THY_NAME.*\" in Haskell file \"$DST\"" || fail "could not re_import $THY"
+  "$ISATOOL" codegen HOL "$THY_NAME" "\"$THY_NAME.*\" in Haskell module_name "$THY_NAME" file \"$DST\"" || fail "could not re_import $THY"
 done
