improved shell interface

diff --git a/bin/import_all b/bin/import_all
--- a/bin/import_all
+++ b/bin/import_all
@@ -1,29 +1,42 @@
 #!/bin/bash
 #
-# $Id$
 # Author: Florian Haftmann, TU Muenchen
 #
 # Roundtrip for all Haskell files in the examples directory.
 
+## environment
+
+PRG="$(basename "$0")"
+HASKABELLE_HOME="$(cd "$(dirname "$0")"; cd "$(pwd -P)"; cd ..; pwd)"
+
+if [ -z "$ISABELLE_HOME" ]
+then
+  ISABELLE=isabelle
+  if type -t isatool > /dev/zero
+  then
+    ISABELLE=isatool
+  fi
+  ISABELLE_HOME="$($ISABELLE getenv -b ISABELLE_HOME)"
+else
+  ISABELLE="$ISABELLE_HOME/bin/isabelle"
+fi
+
+## diagnostics
+
 function fail()
 {
   echo "$1" >&2
-  #exit 2
+  exit 2
 }
 
-EXECPATH="$(dirname "$0")/.."
+## testing
 
-[ -z "$EXECPATH" ] && fail "$0 must be called with explicit path"
-
-[ -z "$ISABELLE_HOME" ] && ISABELLE_HOME="$(isatool getenv -b ISABELLE_HOME)"
-ISATOOL="$ISABELLE_HOME/bin/isatool"
-
-cd "$EXECPATH"
+cd "$HASKABELLE_HOME"
 for SRC in ex/src_hs/*.hs
 do
   DST=ex/dst_thy/
   echo "importing $SRC..."
-  ./bin/import_file "$SRC" "$DST" > /dev/zero 2> /dev/zero || fail "could not import $SRC"
+  bin/import_file "$SRC" "$DST" > /dev/zero 2> /dev/zero || fail "could not import $SRC"
 done
 
 cp -vu misc/Prelude.thy ex/dst_thy/
@@ -33,5 +46,5 @@ do
   THY_NAME="$(basename $THY .thy)"
   DST="../../ex/dst_hs/"
   echo "re-importing $THY_NAME..."
-  "$ISATOOL" codegen HOL "$THY_NAME" "\"$THY_NAME.*\" in Haskell module_name "$THY_NAME" file \"$DST\"" > /dev/zero 2> /dev/zero || fail "could not re-import $THY"
+  "$ISABELLE" codegen HOL "$THY_NAME" "\"$THY_NAME.*\" in Haskell module_name "$THY_NAME" file \"$DST\"" > /dev/zero 2> /dev/zero || fail "could not re-import $THY"
 done
