assuming isabelle/isabelle-process script layout

diff --git a/bin/isabelle b/bin/isabelle
--- a/bin/isabelle
+++ b/bin/isabelle
@@ -2,7 +2,7 @@
 #
 # Author: Florian Haftmann, TU Muenchen
 #
-# Ephermal adapter script for isabelle vs. isatool.
+# Wrapper script for isabelle tool.
 
 ## environment
 
@@ -10,18 +10,13 @@ HASKABELLE_HOME="$(cd "$(dirname "$0")"; cd "$(pwd -P)"; cd ..; pwd)"
 
 if [ -z "$ISABELLE_TOOL" ]
 then
-  if type -t isatool > /dev/zero
+  ISABELLE_INVOKE_HOME="$(cd "$(dirname "$(type -p isabelle)")"; cd ..; cd "$(pwd -P)"; pwd)"
+  if [ "$ISABELLE_INVOKE_HOME" == "$HASKABELLE_HOME" ]
   then
-    ISABELLE_TOOL="$(isatool getenv -b ISATOOL)"
-  else
-    ISABELLE_INVOKE_HOME="$(cd "$(dirname "$(type -p isabelle)")"; cd ..; cd "$(pwd -P)"; pwd)"
-    if [ "$ISABELLE_INVOKE_HOME" == "$HASKABELLE_HOME" ]
-    then
-      echo "Cannot find isabelle executable on PATH=$PATH" >&2
-      exit 2
-    fi
-    ISABELLE_TOOL="$(isabelle getenv -b ISABELLE_TOOL)"
+    echo "Cannot find isabelle executable on PATH=$PATH" >&2
+    exit 2
   fi
+  ISABELLE_TOOL="$(isabelle getenv -b ISABELLE_TOOL)"
 fi
 
 ## execute
