avoid recursion on isabelle wrapper

diff --git a/bin/isabelle b/bin/isabelle
--- a/bin/isabelle
+++ b/bin/isabelle
@@ -14,6 +14,12 @@ then
   then
     ISABELLE_TOOL="$(isatool getenv -b ISATOOL)"
   else
+    ISABELLE_INVOKE_HOME="$(cd "$(dirname "$(type -p isabelle)")"; cd ..; cd "$(pwd -P)"; pwd)"
+    if [ "$ISABELLE_INVOKE_HOME" == "$HASKABELLE_HOME" ]
+    then
+      echo "Cannot find isabelle executable on PATH=$PATH" >&2
+      exit 2
+    fi
     ISABELLE_TOOL="$(isabelle getenv -b ISABELLE_TOOL)"
   fi
 fi
