removed bin/import_only

diff --git a/bin/regression b/bin/regression
--- a/bin/regression
+++ b/bin/regression
@@ -37,12 +37,18 @@ do
   bin/haskabelle "$SRC" "$DST" > /dev/zero 2> /dev/zero || fail "could not import $SRC"
 done
 
-cp -vu misc/Prelude.thy ex/dst_thy/
-cd ex/dst_thy/
-for THY in *.thy
-do
-  THY_NAME="$(basename $THY .thy)"
-  DST="../../ex/dst_hs/"
-  echo "re-importing $THY_NAME..."
-  "$ISABELLE" codegen HOL "$THY_NAME" "\"$THY_NAME.*\" in Haskell module_name "$THY_NAME" file \"$DST\"" > /dev/zero 2> /dev/zero || fail "could not re-import $THY"
-done
+## re-importing
+
+if [ "$1" != "no_reimport" ]
+then
+  cp -vu misc/Prelude.thy ex/dst_thy/
+  cd ex/dst_thy/
+  for THY in *.thy
+  do
+    THY_NAME="$(basename $THY .thy)"
+    DST="../../ex/dst_hs/"
+    echo "re-importing $THY_NAME..."
+    "$ISABELLE" codegen HOL "$THY_NAME" "\"$THY_NAME.*\" in Haskell module_name "$THY_NAME" file \"$DST\"" > /dev/zero 2> /dev/zero || fail "could not re-import $THY"
+  done
+fi
+
