be less verbose

diff --git a/admin/makedist b/admin/makedist
--- a/admin/makedist
+++ b/admin/makedist
@@ -79,8 +79,8 @@ fi
 
 ## building generated files
 
-admin/builddoc || fail "Could not build documentation"
-bin/mk_adapt || fail "Could not build adaption table"
+admin/builddoc > /dev/null || fail "Could not build documentation"
+bin/mk_adapt > /dev/null || fail "Could not build adaption table"
 
 ## include manual
 
@@ -91,7 +91,7 @@ rm -rf doc-src
 
 if [ "$REGRESSION" ]
 then
-  bin/regression || fail "Could not issue regression test"
+  bin/regression || fail "Could not carry out regression test"
 fi
 
 ## remove admin, build
