fixed makedist

diff --git a/admin/makedist b/admin/makedist
--- a/admin/makedist
+++ b/admin/makedist
@@ -90,7 +90,7 @@ rm -rf doc-src
 
 if [ "$REGRESSION" ]
 then
-  bin/regression
+  bin/regression || fail "Could not issue regression test"
 fi
 
 ## remove admin
