fix regression test

diff --git a/admin/makedist b/admin/makedist
--- a/admin/makedist
+++ b/admin/makedist
@@ -93,7 +93,7 @@ rm -rf doc-src
 
 if [ "$REGRESSION" ]
 then
-  bin/regression || fail "Could not carry out regression test"
+  admin/regression || fail "Could not carry out regression test"
 fi
 
 ## remove admin, build
