fix regression test; move regression test to admin/

diff --git a/admin/regression b/admin/regression
--- a/admin/regression
+++ b/admin/regression
@@ -52,10 +52,6 @@ function fail_or_warn()
   fi
 }
 
-## building
-
-cd "$HASKABELLE_HOME"
-lib/buildbin || fail "Could not build source"
 
 ## testing
 
@@ -63,7 +59,7 @@ for SRC in ex/src_hs/*.hs
 do
   DST=ex/dst_thy/
   echo "importing $SRC..."
-  bin/haskabelle "$SRC" "$DST" > /dev/zero 2> /dev/zero || fail "Could not import $SRC"
+  "$HASKABELLE_HOME/admin/haskabelle" "$SRC" "$DST" || fail "Could not import $SRC"
 done
 
 ## re-importing
