do not change working directory: breaks relative paths on the command line

diff --git a/lib/Tools/haskabelle b/lib/Tools/haskabelle
--- a/lib/Tools/haskabelle
+++ b/lib/Tools/haskabelle
@@ -91,11 +91,13 @@ HASKABELLE_BIN="$HASKABELLE_HOME/bin/haskabelle_bin"
 
 if [ -n "$ISABELLE_GHC" ]; then
   BUILDDIR=build
+  (
   cd "$HASKABELLE_HOME"
   mkdir -p "$BUILDDIR" || fail "Cannot create directory $BUILDDIR"
   mkdir -p bin || fail "Cannot create directory bin"
   $ISABELLE_GHC -package haskell-src-exts-0.4.8 --make -O -o bin/haskabelle_bin \
-      -odir "$BUILDDIR" -hidir "$BUILDDIR" -stubdir "$BUILDDIR" "Main.hs" || fail "Cannot build source"
+      -odir "$BUILDDIR" -hidir "$BUILDDIR" -stubdir "$BUILDDIR" "Main.hs"
+  ) || fail "Cannot build source"
 elif [ ! -e "$HASKABELLE_BIN" ]; then
   fail "Cannot build haskabelle_bin as ISABELLE_GHC is not set"
 fi
