component wrapper rebuilds haskabelle whenever possible

diff --git a/lib/Tools/haskabelle b/lib/Tools/haskabelle
--- a/lib/Tools/haskabelle
+++ b/lib/Tools/haskabelle
@@ -80,14 +80,24 @@ shift $(($OPTIND - 1))
 
 ## build
 
+# haskabelle binary
+
+HASKABELLE_BIN="$HASKABELLE_HOME/bin/haskabelle_bin"
+
+if [ -n "$ISABELLE_GHC" ]; then
+  GHC="$ISABELLE_GHC" "$HASKABELLE_HOME/bin/buildbin" || exit $?
+elif [ ! -e "$HASKABELLE_BIN" ]; then
+  fail "Cannot build haskabelle_bin as ISABELLE_GHC is not set"
+fi
+
+
+# adaptation table
+
 if [ "$BUILD_ADAPT" = true ]; then
   "$HASKABELLE_HOME/bin/mk_adapt" $ADAPT_DIR || exit $?
 fi
 
-
 ## main
-
-HASKABELLE_BIN="$HASKABELLE_HOME/bin/haskabelle_bin"
 
 if [ "$SHOW_VERSION" = true ]; then
   "$HASKABELLE_BIN" --internal --version
